//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetaViews.Messages.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AvaliacaoStatusModel
    {
    	
        public AvaliacaoStatusModel()
        {
            this.AvaliacaoModel = new HashSet<AvaliacaoModel>();
        }
    
        public int Id { get; set; }
        public string Descricao { get; set; }
    
        public virtual ICollection<AvaliacaoModel> AvaliacaoModel { get; set; }
    }
}
