//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetaViews.Messages.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClienteAcessoPerfilModel
    {
        public int Id { get; set; }
        public int IdClienteAcesso { get; set; }
        public int IdPaginaAcesso { get; set; }
    
        public virtual ClienteAcessoModel ClienteAcessoModel { get; set; }
        public virtual PaginaAcessoModel PaginaAcessoModel { get; set; }
    }
}
