//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetaViews.Messages.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClienteModel
    {
    	
        public ClienteModel()
        {
            this.LojaModel = new HashSet<LojaModel>();
            this.ClienteAcessoModel = new HashSet<ClienteAcessoModel>();
            this.PalavraRecusadaPadraoClienteModel = new HashSet<PalavraRecusadaPadraoClienteModel>();
            this.ClienteConfiguracaoModel = new HashSet<ClienteConfiguracaoModel>();
            this.BadgeModel = new HashSet<BadgeModel>();
        }
    
        public int Id { get; set; }
        public string CodigoCliente { get; set; }
        public string Nome { get; set; }
        public string CPFCNPJ { get; set; }
        public string Endereco { get; set; }
        public string EnderecoNumero { get; set; }
        public string Bairro { get; set; }
        public string Cidade { get; set; }
        public string CEP { get; set; }
        public bool FlagAtivo { get; set; }
        public System.DateTime DtCadastro { get; set; }
        public string APIKey { get; set; }
    
        public virtual ICollection<LojaModel> LojaModel { get; set; }
        public virtual ICollection<ClienteAcessoModel> ClienteAcessoModel { get; set; }
        public virtual ICollection<PalavraRecusadaPadraoClienteModel> PalavraRecusadaPadraoClienteModel { get; set; }
        public virtual ICollection<ClienteConfiguracaoModel> ClienteConfiguracaoModel { get; set; }
        public virtual ICollection<BadgeModel> BadgeModel { get; set; }
    }
}
