//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetaViews.Messages.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClienteConfiguracaoModel
    {
        public int Id { get; set; }
        public int IdCliente { get; set; }
        public Nullable<bool> ReviewClienteLogado { get; set; }
        public string PaginaRedirecionaLogin { get; set; }
        public Nullable<bool> FlagUploadImagem { get; set; }
        public Nullable<int> TotPageSize { get; set; }
        public Nullable<bool> FaceBookShare { get; set; }
        public Nullable<bool> TwitterShare { get; set; }
        public Nullable<int> FlagTermoAceite { get; set; }
        public string TermoAceite { get; set; }
        public Nullable<bool> FlagQA { get; set; }
    
        public virtual ClienteModel ClienteModel { get; set; }
    }
}
