//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetaViews.Messages.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogErrosModel
    {
        public int Id { get; set; }
        public string Interface { get; set; }
        public string ProtocoloRetorno { get; set; }
        public string CodigoErro { get; set; }
        public string Descricao { get; set; }
        public int TipoMensagem { get; set; }
        public System.DateTime Data { get; set; }
    }
}
