//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetaViews.Messages.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LojaConfiguracaoModel
    {
        public int Id { get; set; }
        public int IdLoja { get; set; }
        public bool ReviewClienteLogado { get; set; }
        public string PaginaRedirecionaLogin { get; set; }
        public bool FlagUploadImagem { get; set; }
        public int TotPageSize { get; set; }
        public bool FaceBookShare { get; set; }
        public bool TwitterShare { get; set; }
        public int FlagTermoAceite { get; set; }
        public string TermoAceite { get; set; }
        public bool FlagQA { get; set; }
        public string GA { get; set; }
    
        public virtual LojaModel LojaModel { get; set; }
    }
}
