//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetaViews.Messages.Models
{
    using Dtos;
    using System;
    using System.Collections.Generic;

    public partial class LojaModel : PaginationDTO
    {
    	
        public LojaModel()
        {

            this.AvaliacaoModel = new HashSet<AvaliacaoModel>();
            this.QAModel = new HashSet<QAModel>();
            this.ClienteAcessoLojaModel = new HashSet<ClienteAcessoLojaModel>();
            this.LojaConfiguracaoModel = new HashSet<LojaConfiguracaoModel>();
            this.ProdutoModel = new HashSet<ProdutoModel>();
            this.NPSLojaModel = new HashSet<NPSLojaModel>();
        }
    
        public int Id { get; set; }
        public int IdCliente { get; set; }
        public string CodigoLoja { get; set; }
        public string Nome { get; set; }
        public System.DateTime DtCadastro { get; set; }
        public string CPFCNPJ { get; set; }
        public string Endereco { get; set; }
        public string EnderecoNumero { get; set; }
        public string Bairro { get; set; }
        public string Cidade { get; set; }
        public string CEP { get; set; }
        public string Url { get; set; }
        public string Logo { get; set; }
        public bool MarketPlace { get; set; }
        public bool FlagAtivo { get; set; }
        public string TermoAceite { get; set; }


        public int s1 { get; set; }
        public int s2 { get; set; }
        public int s3 { get; set; }
        public int s4 { get; set; }
        public int s5 { get; set; }
        public int TotalAvaliacoes { get; set; }
        public double MediaTotal { get; set; }

        //public AvaliacaoTotaisDTO AvaliacaoGeral { get; set; }

        public virtual ClienteModel ClienteModel { get; set; }
        public virtual ICollection<AvaliacaoModel> AvaliacaoModel { get; set; }
        public virtual ICollection<QAModel> QAModel { get; set; }
        public virtual ICollection<ClienteAcessoLojaModel> ClienteAcessoLojaModel { get; set; }
        public virtual ICollection<LojaConfiguracaoModel> LojaConfiguracaoModel { get; set; }
        public virtual ICollection<ProdutoModel> ProdutoModel { get; set; }
        public virtual ICollection<NPSLojaModel> NPSLojaModel { get; set; }
    }
}
