//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetaViews.Messages.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PaginaAcessoModel
    {
    	
        public PaginaAcessoModel()
        {
            this.ClienteAcessoPerfilModel = new HashSet<ClienteAcessoPerfilModel>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }        
        public string Modulo { get; set; }
        public string Descricao { get; set; }
    
        public virtual ICollection<ClienteAcessoPerfilModel> ClienteAcessoPerfilModel { get; set; }
    }
}
