//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetaViews.Messages.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PalavraRecusadaPadraoClienteModel
    {
        public int Id { get; set; }
        public int IdCliente { get; set; }
        public string Nome { get; set; }
    
        public virtual ClienteModel ClienteModel { get; set; }
    }
}
