//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetaViews.Messages.Models
{
    using Dtos;
    using System;
    using System.Collections.Generic;

    public partial class ProdutoModel: PaginationDTO
    {
    	
        public ProdutoModel()
        {
            this.AvaliacaoProdutoModel = new HashSet<AvaliacaoProdutoModel>();
            this.QAProdutoModel = new HashSet<QAProdutoModel>();
        }
    
        public int Id { get; set; }
        public int IdLoja { get; set; }
        public string Nome { get; set; }
        public string Codigo { get; set; }
        public string Departamento { get; set; }
        public string Categoria { get; set; }
        public string SubCategoria { get; set; }
        public string Marca { get; set; }
        public string Link { get; set; }
        public string ImagemProduto { get; set; }
        public System.DateTime DtCadastro { get; set; }
        public System.DateTime DtUltimaAtualizacao { get; set; }
        
        public int s1 { get; set; }
        public int s2 { get; set; }
        public int s3 { get; set; }
        public int s4 { get; set; }
        public int s5 { get; set; }
        public int TotalAvaliacoes { get; set; }
        public double MediaTotal { get; set; }
        

        public virtual ICollection<AvaliacaoProdutoModel> AvaliacaoProdutoModel { get; set; }
        public virtual ICollection<QAProdutoModel> QAProdutoModel { get; set; }
        public virtual LojaModel LojaModel { get; set; }
    }
}
