//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetaViews.Messages.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QAModel
    {
    	
        public QAModel()
        {
            this.QAProdutoModel = new HashSet<QAProdutoModel>();
        }
    
        public int Id { get; set; }
        public int IdLoja { get; set; }
        public int IdQAStatus { get; set; }
        public string ClienteNome { get; set; }
        public string ClienteEmail { get; set; }
        public string ClienteLocalizacao { get; set; }
        public string Pergunta { get; set; }
        public System.DateTime DtPergunta { get; set; }
        public string Resposta { get; set; }
        public Nullable<System.DateTime> DtResposta { get; set; }
        public Nullable<int> IdClienteAcesso { get; set; }
        public Nullable<int> IdBadge { get; set; }
        public Nullable<int> QtdAjudou { get; set; }
        public Nullable<int> QtdNaoAjudou { get; set; }
        public string ModeracaoOBS { get; set; }
        public string RespTerceiroClienteNome { get; set; }
        public string RespTerceiroClienteEmail { get; set; }
        public string RespTerceiroClienteLocalizacao { get; set; }
        public Nullable<int> RespTerceiroStatus { get; set; }
    
        public virtual QAStatusModel QAStatusModel { get; set; }
        public virtual ICollection<QAProdutoModel> QAProdutoModel { get; set; }
        public virtual LojaModel LojaModel { get; set; }
    }
}
