//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetaViews.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AvaliacaoProdutoModel
    {
        public AvaliacaoProdutoModel()
        {
            this.AvaliacaoProdutoPD = new HashSet<AvaliacaoProdutoPDModel>();
        }
    
        public int Id { get; set; }
        public int IdLoja { get; set; }
        public int IdProduto { get; set; }
        public string CodigoCompra { get; set; }
        public string NomeCliente { get; set; }
        public string EmailCliente { get; set; }
        public int AvaliacaoGeral { get; set; }
        public string ComentarioCliente { get; set; }
        public System.DateTime DtEnvioAPI { get; set; }
        public System.DateTime DtAvaliacao { get; set; }
        public System.DateTime DtDisponivel { get; set; }
        public bool FlagAtivo { get; set; }
    
        public virtual LojaModel Loja { get; set; }
        public virtual ProdutoModel Produto { get; set; }
        
        public virtual ICollection<AvaliacaoProdutoPDModel> AvaliacaoProdutoPD { get; set; }
    }
}
