//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetaViews.API.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class AvaliacaoLojaModel
    {
        //public AvaliacaoLojaModel()
        //{
        //    this.AvaliacaoLojaPD = new HashSet<AvaliacaoLojaPDModel>();
        //}
    
        public int Id { get; set; }

        [Required]
        public int IdLoja { get; set; }

        [Required]
        public string NomeCliente { get; set; }
        [Required]
        public string EmailCliente { get; set; }
        public int AvaliacaoGeral { get; set; }
        public string ComentarioCliente { get; set; }
        //public System.DateTime DtEnvioAPI { get; set; }
        public System.DateTime DtAvaliacao { get; set; }
        //public System.DateTime DtDisponivel { get; set; }
        public bool FlagAtivo { get; set; }
    
        //public virtual LojaModel Loja { get; set; }
        
        //public virtual ICollection<AvaliacaoLojaPDModel> AvaliacaoLojaPD { get; set; }
    }
}
