//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetaViews.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AvaliacaoLojaPDModel
    {
        public int Id { get; set; }
        public int IdAvaliacaoLoja { get; set; }
        public int IdLojaPD { get; set; }
        public string RespostaEscolhida { get; set; }
    
        public virtual AvaliacaoLojaModel AvaliacaoLoja { get; set; }
        public virtual LojaPDModel LojaPD { get; set; }
    }
}
