//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetaViews.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClienteModel
    {
        public ClienteModel()
        {
            this.Loja = new HashSet<LojaModel>();
            this.ClienteAcesso = new HashSet<ClienteAcessoModel>();
            this.PalavraRecusadaPadraoCliente = new HashSet<PalavraRecusadaPadraoClienteModel>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public string CPFCNPJ { get; set; }
        public string Endereco { get; set; }
        public string EnderecoNUmero { get; set; }
        public string Bairro { get; set; }
        public string Cidade { get; set; }
        public string CEP { get; set; }
        public bool FlagAtivo { get; set; }
        public System.DateTime DtCadastro { get; set; }
        public string APIKey { get; set; }
        public System.DateTime DtUltimoEnvio { get; set; }
    
        
        public virtual ICollection<LojaModel> Loja { get; set; }
        
        public virtual ICollection<ClienteAcessoModel> ClienteAcesso { get; set; }
        
        public virtual ICollection<PalavraRecusadaPadraoClienteModel> PalavraRecusadaPadraoCliente { get; set; }
    }
}
