//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetaViews.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LojaPDModel
    {
        public LojaPDModel()
        {
            this.AvaliacaoLojaPD = new HashSet<AvaliacaoLojaPDModel>();
        }
    
        public int Id { get; set; }
        public int IdLoja { get; set; }
        public string Pergunta { get; set; }
        public string OpcaoResposta { get; set; }
    
        
        public virtual ICollection<AvaliacaoLojaPDModel> AvaliacaoLojaPD { get; set; }
    }
}
