//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetaViews.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LojaModel
    {
        public LojaModel()
        {
            this.AvaliacaoLoja = new HashSet<AvaliacaoLojaModel>();
            this.Produto = new HashSet<ProdutoModel>();
            this.AvaliacaoProduto = new HashSet<AvaliacaoProdutoModel>();
        }
    
        public int Id { get; set; }
        public int IdCliente { get; set; }
        public string Nome { get; set; }
        public string Url { get; set; }
        public string Logo { get; set; }
        public bool MarketPlace { get; set; }
        public bool FlagAtivo { get; set; }
        public System.DateTime DtCadastro { get; set; }
    
        public virtual ClienteModel Cliente { get; set; }
        
        public virtual ICollection<AvaliacaoLojaModel> AvaliacaoLoja { get; set; }
        
        public virtual ICollection<ProdutoModel> Produto { get; set; }
        
        public virtual ICollection<AvaliacaoProdutoModel> AvaliacaoProduto { get; set; }
    }
}
