//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetaViews.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdutoPDModel
    {
        public ProdutoPDModel()
        {
            this.AvaliacaoProdutoPD = new HashSet<AvaliacaoProdutoPDModel>();
        }
    
        public int Id { get; set; }
        public int IdProduto { get; set; }
        public string Pergunta { get; set; }
        public string OpcaoResposta { get; set; }
    
        public virtual ProdutoModel Produto { get; set; }
        
        public virtual ICollection<AvaliacaoProdutoPDModel> AvaliacaoProdutoPD { get; set; }
    }
}
