//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetaViews.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdutoModel
    {
        public ProdutoModel()
        {
            this.ProdutoPD = new HashSet<ProdutoPDModel>();
            this.AvaliacaoProduto = new HashSet<AvaliacaoProdutoModel>();
        }
    
        public int Id { get; set; }
        public int IdLoja { get; set; }
        public string Sku { get; set; }
        public string Nome { get; set; }
        public string Categoria { get; set; }
        public decimal Preco { get; set; }
        public bool FlagAtivo { get; set; }
        public System.DateTime DtCadastro { get; set; }
    
        
        public virtual ICollection<ProdutoPDModel> ProdutoPD { get; set; }
        public virtual LojaModel Loja { get; set; }
        
        public virtual ICollection<AvaliacaoProdutoModel> AvaliacaoProduto { get; set; }
    }
}
